### PR TITLE
initial table test

### PR DESCRIPTION
**Pull request by craigsteffen**
Adding a (possibly unlinked) page to demo tables in RST.

We will use this pull request to test communicating with email, and email notifications. 

If we have things configured correctly, Peter and Wedding will not get notifications about the initial PR nor from this comment.

### CODE REVIEW

**Comment by craigsteffen** [comment]
@pmenstrom @wjackson-gh 
Ok gents, I created this pull request.  I banged around with five revisions to get the table to work (it turns out that in RST files, there has to be a blank line before the beginning of the table or else it doesn't render.  

If you read this in email, please just reply to the email to make sure that comments get re-inserted into the pull request. 

After that, could you go to the pull request page and click on "table_demo_page" somewhere on that page to go to that branch, then go into the "docs" folder, then into the "source" folder, then click on "table.rst".  (If you don't see that file in the "source" directory, you may be in the wrong branch.  Go to the branch pulldown menu above the directory window and go to the "table_demo_page" branch).  Please confirm that you see the 2x2 table that I put in the table.rst demo file in the file preview.  

Thanks.  Talk to you next week.

**Comment by pmenstrom** [comment]
I got the email, I will reply in the pull request when I get home after lunch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wjackson-gh** [comment]
I got the email.

**Comment by craigsteffen** [comment]
Awesome.  So that part's working.  Thanks, everyone.

**Comment by craigsteffen** [comment]
Hi @skappes, 

If this is working correctly, you're reading this in an email.  Please feel free to reply to this email saying "yep, I got it".  

I'll go over more of the details when we meet on Monday.  Have a good weekend; talk to you then.  

Craig Steffen

**Comment by pmenstrom** [comment]
I see the 2X2 table in table.rst and I added this comment in the branch on the github webpage.

**Comment by skappes** [comment]
yep, I got it
________________________________

**Comment by craigsteffen** [comment]
Here is a link to see the current version of the proposed_changes branch, which is what's being reviewed in this pull request.
https://ncsau-of-i-nightingale-real.readthedocs-hosted.com/en/proposed_changes/

The above is the front page.  Here is a link to *that* branch to the table that's also in this pull request (which isn't linked and thus is hidden unless you have the filename or a direct link).
https://ncsau-of-i-nightingale-real.readthedocs-hosted.com/en/proposed_changes/table.html

We'll review these links in the call that happens in 20 minutes (Thursday morning August 11).

Craig

**Comment by craigsteffen** [comment]
@wjackson-gh Weddie, you probably won't be able to view those links until you accept the invitiation to create an account on readthedocs.com.  Once you do, however, those links should work for you, and you'll go to a readthedocs page that's the Nightingale page, and the identifier at the bottom left of the page should say "proposed_changes" rather than "latest".  

Once you've done that, please verify that both links work for you and you can see the rendered pages.  

Craig

**Review by skappes — APPROVED** [review]
looks good

**Comment by wjackson-gh** [comment]
I'm in Peoria to pick up my daughter from the airport. Trying to connect is horrible.  Sorry guys
________________________________

**Comment by pmenstrom** [comment]
You had your calendar marked as being out, you are fine.

**Pull request merged**
