### PR TITLE
slurm only on login01

### PR DESCRIPTION
**Pull request by craigsteffen**
Adding specific verbiage to point out that slurm commands may only be used on login01.

### CODE REVIEW

**Comment by craigsteffen** [comment]
@pmenstrom 

Do these changes cover what you think we should say?  I mentioned login01 the first place that slurm is mentioned on that page.  

@lhelms2 This is a change requested by Peter.  Any objections or tweaks you'd like for these changes?

**Comment by craigsteffen** [comment]
https://docs.ncsa.illinois.edu/systems/nightingale/en/proposed_changes/user_guide/running_jobs.html#accessing-the-compute-nodes

Here is the built page with the changed paragraph at the top.

**Comment by lhelms2** [comment]
What about login02?

I made a very minor editorial change, but otherwise I'm good (assuming login02 isn't also an option).

**Comment by lhelms2** [comment]
@craigsteffen @pmenstrom 
Do you know the answer to the login02 question?

**Comment by pmenstrom** [comment]
I tried out SLURM commands on ng-login02 and they work there as well.

**Review by lhelms2 — APPROVED** [review]
I updated to include login02 as well.

**Pull request merged**
