### PR TITLE
Add File Permissions section

### PR DESCRIPTION
**Pull request by lhelms2**
Added "File and Directory Permissions" section to File Management to tell users not to grant permissions to "others". Also added a warning to the beginning of the "Creating and Editing Files" section in File Management.

You can view it built in Read the Docs here: https://docs.ncsa.illinois.edu/systems/nightingale/en/proposed_changes/user_guide/file_mgmt.html

### CODE REVIEW

**Comment by lhelms2** [comment]
@pmenstrom @wjackson-gh 
Can you please take a look at this PR? 
I'd like to merge after 12pm on Friday (2/23), assuming I've gotten at least one approving review by then.

Thank you,
Lillian

**Comment by pmenstrom** [comment]
Can you give a link to the request?

**Review by pmenstrom — APPROVED** [review]
Looks great!

**Comment by lhelms2** [comment]
@wjackson-gh @pmenstrom thank you for such quick reviews! I'll get it merged today.

**Pull request merged**
