### PR TITLE
Proposed changes - Software, Running Jobs, Visualization, Containers

### PR DESCRIPTION
**Pull request by lhelms2**
@pmenstrom , @craigsteffen , @wjackson-gh 

The Software, Running Jobs, Visualization, and Containers sections have been revised and are ready for the review/merge process.

I'm planning to merge these changes into main at **12pm on Friday (10/27)** (assuming I've gotten at least one review).

Once these are updates are merged, I’ll move on to another set of sections.

Thank you,
Lillian

### CODE REVIEW

**Review by craigsteffen — APPROVED** [review]
These changes all look good.  (I see you got rid of the raw html tags--thanks!).  I see you re-rendered a bunch of the tables as well.  

I'll take another spin through these pages to make sure that the table formatting makes sense when rendered, but this looks good to me.

**Comment by craigsteffen** [comment]
I'm trying to move the programming_environment.rst file out into the user_guide directory, but I can't seem to do it.  I'll work on it.

**Review by wjackson-gh — APPROVED** [review]
That layout works for me.

**Comment by lhelms2** [comment]
@craigsteffen, @wjackson-gh, thank you for review these changes! Merging into main now.

**Pull request merged**
