### PR TITLE
Correct settings for HTTPS_PROXY & R_LIBS env vars

### PR DESCRIPTION
**Pull request by wjackson-gh**
Add a step to set the HTTPS_PROXY environment variable so that a R packages can be downloaded directly from cran.r-project.org to NG.  Also correctly set the R_LIBS environment variable.

### CODE REVIEW

**Comment by craigsteffen** [comment]
Cool.  I'll add my two sets of changes to this.  I'll try to do it in the next couple of days.  

Is that soon enough, @wjackson-gh ?

**Comment by wjackson-gh** [comment]
Sure, whatever is convenient for you.

**Comment by craigsteffen** [comment]
Ok.  There were already several changes in the branch proposed_changes from a few weeks ago, that I guess we forgot to roll into main.  I guess we should have approved those and pushed to main.  

When creating edit branches in the future, please edit directoy to proposed_changes or else split the branch from proposed_changes, rather than from main.  

I will rebase this branch so that we're considering all the changes together.  I'll try to get a version ready for review today.

**Comment by craigsteffen** [comment]
@wjackson-gh I'm going to close this pull request and create a new one against the current proposed_changes to review.

**Pull request closed without merging**
