### PR TITLE
Sandie branch

### PR DESCRIPTION
**Pull request by skappes**
Merging version to be reviewed by NG staff.

### CODE REVIEW

**Comment by craigsteffen** [comment]
This is certainly fine to merge into main so that it can be pushed to the committee for any further changes/edits.  I will go ahead and approve this when it's ready.  The page looks fine and the navigation generally works.  

There are a few things I did notice:
- The link to "module commands" at the top of the "Installed software" page doesn't work.  
- There are email links to "email help@" in a couple of the pages that we say "we don't have that" (like visualization).  I think those would be better to be links to the help page, where we specifically spell out how to send in new tickets, including putting "Nightingale" in the subject and so on.  

Editorially, I think this hierarchy is deeper than we need, but I think that's just a difference between my preferences and yours.

**Review by craigsteffen — APPROVED** [review]
There are a few things to tweak, but this is fine for general review.

**Comment by skappes** [comment]
I guess we will have to agree to disagree on the hierarchy. I do agree about linking to the Getting Help page. That was something I was going to point out to the reviewers. The Getting Help page needs more work as well.

I'll get the using modules links fixed. I would swear they were working... Can I just edit directly on main?

Thanks,

Sandie
________________________________

**Comment by craigsteffen** [comment]
I have just given you special access (which I don't have myself) to bypass
pull requests and commit directly to main.  I advise you to mostly not to
use that power, but mostly commit to a separate branch, review carefully,
and then merge a bunch all at once to main as you've been doing.

Craig

**Pull request merged**
