### PR TITLE
Major file re-organization

### PR DESCRIPTION
**Pull request by lhelms2**
@craigsteffen @wjackson-gh @pmenstrom 

File re-organization, I kept content changes to a minimum, those will be done after this merge is complete. 

The pages under the User Guide heading are in the user_guide folder, the rest are just in source. Images associated with user_guide pages are in the user_guide/images folder. Images associated with the other pages are in the source/images folder. All of the unused files (including images) are consolidated into the not_used folder; the .rst files were changed to .txt so they don’t show up in search results. The quick_start, faq, and support_services files were crated but no content added yet and they’re not linked in the toctree. The under_review folder is the temporary holding place for the 3 files that I mentioned at the meeting yesterday that are currently not linked anywhere but possibly should be (I’ll be sending a separate email on those).

Please take a look and let me know if you have any questions.
Thank you,
Lillian

### CODE REVIEW

**Comment by pmenstrom** [comment]
The comments are all consistent with the changes that Lillian described. I paged through read-the-docs and didn't see anything broken.

**Review by pmenstrom — APPROVED** [review]
Looks good.

**Review by wjackson-gh — APPROVED** [review]

**Comment by craigsteffen** [comment]
Thanks for the kick, @lhelms2 .  I'm looking at it now.

**Review by craigsteffen — APPROVED** [review]
This all looks good.  Very nice and unified, as advertised.  I would be fine rolling this into main when it's done with the editorial phase.

**Comment by lhelms2** [comment]
@craigsteffen I was intending to merge this into main, as is, and then starting on editorial changes after. 
Do you think it's better for the user to have it all (re-org and editorial) updated at once?

**Comment by craigsteffen** [comment]
I agree that merging this now is the better plan.  I will attempt one more time to check with Cindy.  I'll let you know if I hear anything.  I'll get back to you before my 9am central meeting.

**Comment by craigsteffen** [comment]
I asked Cindy about this in slack and she said: "Agreed. I think merge now is the right answer.".  So full speed ahead.

**Pull request merged**
